-- ============================================================
-- S.E.B.A — Supabase Schema
-- Run this in your Supabase SQL Editor (Dashboard → SQL Editor)
-- ============================================================

-- Transactions table
CREATE TABLE IF NOT EXISTS public.transactions (
    id              BIGSERIAL PRIMARY KEY,
    user_id         TEXT         NOT NULL,          -- Supabase Auth UUID (or demo UUID)
    amount          NUMERIC(12, 2) NOT NULL,
    date            DATE         NOT NULL,
    merchant        TEXT         NOT NULL,
    category        TEXT         NOT NULL DEFAULT 'Misc',
    is_impulsive    BOOLEAN      NOT NULL DEFAULT FALSE,
    impulse_reason  TEXT,                           -- Human-readable reason for the flag
    source          TEXT         NOT NULL DEFAULT 'sms',  -- 'sms' | 'statement' | 'json'
    raw_text        TEXT,
    created_at      TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

-- Index for fast per-user queries (used by all endpoints)
CREATE INDEX IF NOT EXISTS idx_transactions_user_id
    ON public.transactions (user_id);

-- Index for date-range filtering
CREATE INDEX IF NOT EXISTS idx_transactions_date
    ON public.transactions (date DESC);

-- Index for category filtering
CREATE INDEX IF NOT EXISTS idx_transactions_category
    ON public.transactions (category);

-- ── Row Level Security (optional — disable for server-side service role) ──────
-- The backend uses the SERVICE ROLE key which bypasses RLS automatically.
-- Enable RLS only if you also expose this table to the frontend directly.

-- ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;

-- CREATE POLICY "Users can view own transactions"
--     ON public.transactions FOR SELECT
--     USING (auth.uid()::text = user_id);

-- CREATE POLICY "Users can insert own transactions"
--     ON public.transactions FOR INSERT
--     WITH CHECK (auth.uid()::text = user_id);

-- ── Users table (for username/password auth) ──────────────────────────────────
-- Run in Supabase SQL Editor → New Query
CREATE TABLE IF NOT EXISTS public.seba_users (
    id            TEXT         PRIMARY KEY,   -- UUID string generated by backend
    username      TEXT         NOT NULL UNIQUE,
    password_hash TEXT         NOT NULL,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_seba_users_username ON public.seba_users (username);

